### ISSUE TITLE
NullPointerException running example test from Intellij

### ISSUE THREAD

**Issue by dmitry-workato** [Zhiqiang-Wu/idea-jcstress-plugin#2]
Test code:

```
package org.bufistov;

import org.openjdk.jcstress.annotations.Actor;
import org.openjdk.jcstress.annotations.Expect;
import org.openjdk.jcstress.annotations.JCStressTest;
import org.openjdk.jcstress.annotations.Outcome;
import org.openjdk.jcstress.annotations.State;
import org.openjdk.jcstress.infra.results.II_Result;

import static org.openjdk.jcstress.annotations.Expect.ACCEPTABLE;

@JCStressTest
@State
@Outcome(id = "1, 2", expect = Expect.ACCEPTABLE, desc = "T1 updated, then T2 updated.")
@Outcome(id = "2, 1", expect = Expect.ACCEPTABLE, desc = "T2 updated, then T1 updated.")
@Outcome(id = "1, 1", expect = Expect.ACCEPTABLE, desc = "Both T1 and T2 updated concurrently.")
public class VolatileIncrementAtomicityTest {
    volatile int v;

    @Actor
    void actor1(II_Result r) {
        r.r1 = ++v;
    }

    @Actor
    void actor2(II_Result r) {
        r.r2 = ++v;
    }
}
```

Output last lines:
```
----- [OK] [-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=55179:/Applications/IntelliJ IDEA.app/Contents/bin, -Dfile.encoding=UTF-8, -Dsun.stdout.encoding=UTF-8, -Dsun.stderr.encoding=UTF-8, -XX:+StressLCM, -XX:+StressGCM, -XX:+StressIGVN, -XX:+StressCCP]

Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:168)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:88)
	at org.openjdk.jcstress.infra.runners.TestList.getTests(TestList.java:51)
	at org.openjdk.jcstress.infra.runners.TestList.tests(TestList.java:104)
	at org.openjdk.jcstress.JCStress.getTests(JCStress.java:200)
	at org.openjdk.jcstress.JCStress.run(JCStress.java:69)
	at org.openjdk.jcstress.Main.main(Main.java:60)

Process finished with exit code 1
```

**Comment by MolchanovDmitry** [comment]
The same
```java
import org.openjdk.jcstress.annotations.Actor;
import org.openjdk.jcstress.annotations.JCStressTest;
import org.openjdk.jcstress.annotations.State;
import org.openjdk.jcstress.infra.results.II_Result;

@JCStressTest
@State
public class SimpleTest {
    int x;
    int y;

    @Actor
    public void threadP(II_Result r){
        x = 1;
        r.r1 = y;
    }

    @Actor
    public void threadQ(II_Result r){
        y = 1;
        r.r2 = x;
    }
}

```

<details>
  <summary>Output</summary>

  ```
  Java Concurrency Stress Tests
---------------------------------------------------------------------------------
Rev: null, built by null with null at null

Burning up to figure out the exact CPU count....... done!

Probing the target OS:
 (all failures are non-fatal, but may affect testing accuracy)

----- [N/A] Trying to set global affinity with taskset
Cannot run program "taskset": error=2, No such file or directory
----- [N/A] Trying to set per-thread affinity with syscalls
Not implemented

Initializing and probing the target VM:
 (all failures are non-fatal, but may affect testing accuracy)

----- [OK] Unlocking diagnostic VM options
----- [OK] Disabling performance data collection
----- [OK] Checking for C1 availability
----- [OK] Checking for C2 availability
----- [OK] Checking for biased locking support
----- [OK] Trimming down the VM heap size to 256M
----- [OK] Enabling Java heap pre-touch
----- [OK] Trimming down the number of parallel GC threads
----- [OK] Trimming down the number of concurrent GC threads
----- [OK] Trimming down the number of G1 concurrent refinement GC threads
----- [OK] Trimming down the number of compiler threads
----- [OK] Testing @Contended works on all results and infra objects
----- [OK] Unlocking debug information for non-safepoints
----- [OK] Unlocking C2 local code motion randomizer
----- [OK] Unlocking C2 global code motion randomizer
----- [OK] Unlocking C2 iterative global value numbering randomizer
----- [OK] Unlocking C2 conditional constant propagation randomizer
----- [OK] Checking if C2 randomizers accept stress seed
----- [OK] Testing allocation profiling
----- [OK] Testing Thread.onSpinWait
----- [OK] Testing PrintAssembly
----- [OK] Testing compiler directives

Probing what VM configurations are available:
 (failures are non-fatal, but may miss some interesting cases)
 (split compilation is requested and compiler directives are available)

----- [OK] [-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=57642:/Applications/IntelliJ IDEA CE.app/Contents/bin, -Dfile.encoding=UTF-8, -XX:+UseBiasedLocking]
----- [OK] [-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=57642:/Applications/IntelliJ IDEA CE.app/Contents/bin, -Dfile.encoding=UTF-8, -XX:-UseBiasedLocking]
----- [OK] [-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=57642:/Applications/IntelliJ IDEA CE.app/Contents/bin, -Dfile.encoding=UTF-8, -XX:+UseBiasedLocking, -XX:+StressLCM, -XX:+StressGCM, -XX:+StressIGVN, -XX:+StressCCP]
----- [OK] [-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=57642:/Applications/IntelliJ IDEA CE.app/Contents/bin, -Dfile.encoding=UTF-8, -XX:-UseBiasedLocking, -XX:+StressLCM, -XX:+StressGCM, -XX:+StressIGVN, -XX:+StressCCP]

Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Unknown Source)
	at java.base/java.io.InputStreamReader.<init>(Unknown Source)
	at org.openjdk.jcstress.infra.runners.TestList.getTests(TestList.java:51)
	at org.openjdk.jcstress.infra.runners.TestList.tests(TestList.java:104)
	at org.openjdk.jcstress.JCStress.getTests(JCStress.java:200)
	at org.openjdk.jcstress.JCStress.run(JCStress.java:69)
	at org.openjdk.jcstress.Main.main(Main.java:60)

Process finished with exit code 1

  ```
</details>

**Comment by Zhiqiang-Wu** [comment]
Please use the latest version of jcstress and use private variables.

**Comment by jvma0** [comment]
Try this one [Task fails with NPE #27](https://github.com/reyerizo/jcstress-gradle-plugin/issues/27#issuecomment-1440707745)
